### ISSUE TITLE
styled-jsx resolve handling

### ISSUE THREAD

**Issue by Simounet** [styled-components/vim-styled-components#67]
Hi there,
I know that this is a bit out of scope but can I add the expected CSS syntax for this code?
```css
const foo = css.resolve`
  .bar {
    font-size: 1.3rem;
  }
`;
```
It comes from [styled-jsx](https://www.npmjs.com/package/styled-jsx#external-css-and-styles-outside-of-the-component).

Have a nice day.
